// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using CerebellumRestLib.Models.Enums;
using Newtonsoft.Json;

namespace CerebellumRestLib.Models.JSON.Entities
{
    public class Attachment
    {
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Assigned name of the file after upload.
        /// </summary>
        [JsonProperty("file")]
        public string File { get; set; }

        /// <summary>
        /// Original file name.
        /// </summary>
        [JsonProperty("file_name")]
        public string FileName { get; set; }

        /// <summary>
        /// File description.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }

        /// <summary>
        /// Type of the file.
        /// </summary>
        [JsonProperty("file_type")]
        public FileType FileType { get; set; }

        /// <summary>
        /// Only for FileType.Photo. Set this photo as main.
        /// </summary>
        [JsonProperty("main_photo")]
        public bool? MainPhoto { get; set; }

        /// <summary>
        /// StickerId which would be assigned to this file.
        /// </summary>
        [JsonProperty("sticker_id")]
        public int? StickerId { get; set; }

        [JsonProperty("file_source")]
        public string FileSource { get; set; }

        [JsonProperty("create_date")]
        public long? CreateDate { get; set; }

        [JsonProperty("attachment")]
        public AttachmentInfo AttachmentInfo { get; set; }

        [JsonProperty("origin")]
        public Origin Origin { get; set; }

        [JsonProperty("author")]
        public Author Author { get; set; }

        [JsonProperty("sample_matching")]
        public double? SampleMatching { get; set; }

        [JsonProperty("parent_photo_id")]
        public long? ParentPhotoId { get; set; }
    }
}
