// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using CerebellumRestLib.Models.Base;
using Newtonsoft.Json;

namespace CerebellumRestLib.Models.JSON.Entities
{
    public class UserEdit : JsonBase
    {
        [JsonProperty("id")]
        public int? Id { get; set; }

        [JsonProperty("login")]
        public string Login { get; set; }

        [JsonProperty("paswd")]
        public string Password { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("ur_fio")]
        public string UrFio { get; set; }

        [JsonProperty("ur_address")]
        public string UrAddress { get; set; }

        [JsonProperty("status")]
        public int? Status { get; set; }

        [JsonProperty("organization_id")]
        public int? OrganizationId { get; set; }

        [JsonProperty("role_id")]
        public int? RoleId { get; set; }

        [JsonProperty("fio")]
        public string Fio { get; set; }

        [JsonProperty("passport")]
        public string Passport { get; set; }

        [JsonProperty("avatar_file_name")]
        public string AvatarFileName { get; set; }

        [JsonProperty("tags")]
        public UserTagsEdit UserTags { get; set; }
        
        [JsonProperty("type")]
        public UserType UserType { get; set; }

        [JsonProperty("gis_editor_access")]
        public bool? GisEditorAccess { get; set; }

        [JsonProperty("blocked")]
        public bool? Blocked { get; set; }

        [JsonProperty("tracking")]
        public bool? Tracking { get; set; }
    }
}
