// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using CerebellumRestLib.Models.Base;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace CerebellumRestLib.Models.JSON.Entities
{
    public class WorkTypeEdit : JsonBase
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; } = "default_icon.png";

        [JsonProperty("default_type")]
        public bool DefaultType { get; set; }

        [JsonProperty("period_of_review_in_sec")]
        public int? PeriodOfReviewInSec { get; set; }

        [JsonProperty("deadline_type")]
        public string DeadlineType { get; set; } = "AT_CREATE";

        [JsonProperty("departments")]
        public List<int> Departments { get; set; }

        [JsonProperty("group_id")]
        public int? GroupId { get; set; }
    }

}
