// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using CerebellumRestLib.Models.Base;
using CerebellumRestLib.Models.JSON.Entities;
using Newtonsoft.Json;

namespace CerebellumRestLib.Models.JSON.Requests
{

    public class AttachmentsRequest : JsonBase
    {
        [JsonProperty("attachments")]
        public Attachment[] Attachments { get; set; }
    }

}
